// AUTO-GENERATED by etl/process_report.py — do not edit by hand.
// Data lives in Supabase only (private). For a local preview
// without Supabase, re-run the ETL with --embed.
window.REPORT_DATA = { range: null, transactions: [] };
