#!/usr/bin/env python3
"""
============================================================
3PL Warehouse Operations Dashboard — ETL
============================================================
Source of truth: the raw warehouse Excel exports (inbound +
outbound). Exports TRANSACTION-LEVEL rows so the dashboard can
filter by any date period and recompute all report views live.

Usage:
  python3 etl/process_report.py \
      --inbound  inbound_export.xlsx \
      --outbound outbound_export.xlsx \
      [--push]

Outputs:
  js/data.js                   -> row-level dataset for the dashboard
  supabase/seed_generated.sql  -> raw rows for the warehouse_transactions table

With --push (env vars SUPABASE_URL + SUPABASE_SERVICE_KEY set),
rows are upserted into Supabase directly (live update).

Requires: pandas, openpyxl, requests (for --push)
"""

import argparse, json, os, re, sys
import pandas as pd

ISO_CNTR = re.compile(r"^[A-Z]{4}\s?\d{7}")

def pick_col(df, candidates, label, required=True):
    for c in candidates:
        if c in df.columns:
            return c
    if required:
        sys.exit(f"ERROR: no '{label}' column found. Tried {candidates}.\nColumns: {list(df.columns)}")
    return None

def load(path, direction):
    df = pd.read_excel(path)
    cols = {
        "date":  pick_col(df, ["Created On", "Delivery Date (Plan)", "Date"], "date"),
        "staff": pick_col(df, ["Created By"], "staff"),
        "vol":   pick_col(df, ["Vol in M3", "Volume", "CBM"], "volume"),
        "code":  pick_col(df, ["Ship-from", "Ship-From"] if direction == "IMP"
                          else ["Ship-To", "Final Ship-To Party", "Sold-to Party"], "party code"),
        "name":  pick_col(df, ["Ship-From Party Description"] if direction == "IMP"
                          else ["Ship-To Party Description", "Final Ship-To Party Description",
                                "Sold-to Party Description"], "party name"),
        "doctype": pick_col(df, ["Document Type"], "doc type", required=False),
        "cc":      pick_col(df, ["Container Code"], "container code", required=False),
        "doc":     pick_col(df, ["Document"], "document no", required=False),
    }
    df[cols["date"]] = pd.to_datetime(df[cols["date"]], errors="coerce")
    df = df[df[cols["date"]].notna()]
    df[cols["vol"]] = pd.to_numeric(df[cols["vol"]], errors="coerce").fillna(0)
    rows = []
    for _, r in df.iterrows():
        code = str(r[cols["code"]]).strip()
        name = str(r[cols["name"]]).strip()
        if not code or code.lower() == "nan":
            continue
        dt = str(r.get(cols["doctype"], "") or "").upper()
        cc = str(r.get(cols["cc"], "") or "").strip().upper()
        if cc.lower() == "nan":
            cc = ""
        is_cntr = bool(
            dt in ("Z4FI", "Z4HI") or ISO_CNTR.match(cc)
            or "CNTR" in cc or "40FT" in cc or "40 FT" in cc
            or "20FT" in cc or "20 FT" in cc
        )
        rows.append({
            "d": f"{r[cols['date']]:%Y-%m-%d}",
            "dir": direction,
            "staff": str(r[cols["staff"]]).strip(),
            "code": code,
            "name": name,
            "vol": round(float(r[cols["vol"]]), 3),
            "cntr": (is_cntr if direction == "IMP" else False),
            "cc": cc if (is_cntr and direction == "IMP") else "",
            "doc": str(r.get(cols["doc"], "") or "").strip(),
        })
    return rows

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inbound", required=True)
    ap.add_argument("--outbound")
    ap.add_argument("--push", action="store_true")
    ap.add_argument("--embed", action="store_true",
                    help="ALSO embed data into js/data.js for LOCAL preview only. "
                         "Never commit an embedded data.js to a public repo.")
    args = ap.parse_args()

    tx = load(args.inbound, "IMP")
    if args.outbound:
        tx += load(args.outbound, "EXP")
    else:
        print("NOTE: no outbound file — EXP side will be empty.")
    tx.sort(key=lambda r: (r["d"], r["dir"], r["staff"]))

    dates = sorted({r["d"] for r in tx})
    data = {"range": {"min": dates[0], "max": dates[-1]}, "transactions": tx}

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    js_path = os.path.join(root, "js", "data.js")
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by etl/process_report.py — do not edit by hand.\n")
        if args.embed:
            f.write("// WARNING: contains real warehouse data for LOCAL preview.\n")
            f.write("// Do NOT commit this version to a public repository.\n")
            f.write("window.REPORT_DATA = " + json.dumps(data, ensure_ascii=False) + ";\n")
            print(f"Wrote {js_path} (EMBEDDED preview: {len(tx)} transactions — do not commit)")
        else:
            f.write("// Data lives in Supabase only (private). For a local preview\n")
            f.write("// without Supabase, re-run the ETL with --embed.\n")
            f.write("window.REPORT_DATA = { range: null, transactions: [] };\n")
            print(f"Wrote {js_path} (empty stub — data stays in Supabase only)")

    esc = lambda s: str(s).replace("'", "''")
    lines = [
        "-- AUTO-GENERATED by etl/process_report.py",
        f"-- {dates[0]} -> {dates[-1]} | {len(tx)} rows",
        f"delete from warehouse_transactions where tx_date between '{dates[0]}' and '{dates[-1]}';",
        "insert into warehouse_transactions (tx_date, direction, staff, prin_code, prin_name, vol_cbm, is_container, container_code, document_no) values",
    ]
    lines.append(",\n".join(
        f"  ('{r['d']}', '{r['dir']}', '{esc(r['staff'])}', '{esc(r['code'])}', "
        f"'{esc(r['name'])}', {r['vol']}, {str(r['cntr']).lower()}, '{esc(r['cc'])}', '{esc(r['doc'])}')"
        for r in tx) + ";")
    sql_path = os.path.join(root, "supabase", "seed_generated.sql")
    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {sql_path}")

    if args.push:
        url, key = os.environ.get("SUPABASE_URL"), os.environ.get("SUPABASE_SERVICE_KEY")
        if not url or not key:
            sys.exit("ERROR: --push needs SUPABASE_URL and SUPABASE_SERVICE_KEY env vars.")
        import requests
        h = {"apikey": key, "Authorization": f"Bearer {key}", "Content-Type": "application/json"}
        base = url.rstrip("/") + "/rest/v1/warehouse_transactions"
        requests.delete(base, params={"tx_date": f"gte.{dates[0]}", "and": f"(tx_date.lte.{dates[-1]})"},
                        headers=h, timeout=60)
        payload = [{"tx_date": r["d"], "direction": r["dir"], "staff": r["staff"],
                    "prin_code": r["code"], "prin_name": r["name"], "vol_cbm": r["vol"],
                    "is_container": r["cntr"], "container_code": r["cc"], "document_no": r["doc"]}
                   for r in tx]
        for i in range(0, len(payload), 500):
            resp = requests.post(base, headers=h, json=payload[i:i+500], timeout=120)
            resp.raise_for_status()
        print(f"Pushed {len(payload)} rows to Supabase. Dashboard is live.")

    imp = [r for r in tx if r["dir"] == "IMP"]
    exp = [r for r in tx if r["dir"] == "EXP"]
    print("\n--- SUMMARY (full file range) ---")
    print(f"IMP: {len(imp)} jobs, {round(sum(r['vol'] for r in imp),3)} CBM "
          f"({len({r['cc'] for r in imp if r['cntr'] and r['cc']})} unique containers)")
    print(f"EXP: {len(exp)} jobs, {round(sum(r['vol'] for r in exp),3)} CBM")

if __name__ == "__main__":
    main()
